/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/events/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description No pagination (YAGNI, same reasoning as list_teams) — revisit if the
         *     games table grows large enough that this becomes a real concern.
         */
        get: operations["list_games_events_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game
         * @description The read endpoint posts/'s EventMention.game_id will point to once
         *     posts/ exists (Phase 2 proper, not this unit).
         */
        get: operations["get_game_events_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Teams
         * @description No pagination — the NBA team set is ~30 rows, small and stable
         *     (YAGNI, wiki/CodeContext/Modules/0x02-events.md).
         */
        get: operations["list_teams_events_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_events_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/thread/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_feed_thread__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Version */
        get: operations["health_version_health_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload */
        post: operations["create_upload_media_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media */
        get: operations["get_media_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preference */
        get: operations["get_preference_notifications_preference_get"];
        /** Update Preference */
        put: operations["update_preference_notifications_preference_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Notification */
        post: operations["clear_notification_notifications__notification_id__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Post */
        post: operations["create_post_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like */
        post: operations["like_posts__post_id__like_post"];
        /** Unlike */
        delete: operations["unlike_posts__post_id__like_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Replies
         * @description Direct replies only, oldest first (natural thread reading order).
         *     Returns an empty list both when the post has no replies and when the
         *     post doesn't exist at all -- those two cases look the same here, and
         *     that's fine (a caller who needs to know the post itself exists already
         *     has GET /posts/{post_id} for that).
         */
        get: operations["list_replies_posts__post_id__replies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{post_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_posts__post_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Accounts */
        get: operations["search_accounts_search_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Games */
        get: operations["search_games_search_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/games/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Game Filters
         * @description Teams come from the existing GET /events/teams -- not duplicated
         *     here, per wiki/CodeContext/Modules/0x07-search.md.
         */
        get: operations["game_filters_search_games_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Posts */
        get: operations["search_posts_search_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Profile */
        post: operations["create_profile_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_users_me_delete"];
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_users_me_patch"];
        trace?: never;
    };
    "/users/me/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Following */
        get: operations["get_my_following_users_me_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow User */
        post: operations["follow_user_users__user_id__follow_post"];
        /** Unfollow User */
        delete: operations["unfollow_user_users__user_id__follow_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResult */
        AccountResult: {
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Profile Picture Media Id */
            profile_picture_media_id: number | null;
            /** Username */
            username: string;
        };
        /** AccountsPage */
        AccountsPage: {
            /** Items */
            items: components["schemas"]["AccountResult"][];
            /** Next Offset */
            next_offset: number | null;
        };
        /** AuthorView */
        AuthorView: {
            /** Id */
            id: number;
            /** Profile Picture Media Id */
            profile_picture_media_id: number | null;
            /** Username */
            username: string;
        };
        /** CreatePostRequest */
        CreatePostRequest: {
            /**
             * Is Reply
             * @default false
             */
            is_reply: boolean;
            /**
             * Is Repost
             * @default false
             */
            is_repost: boolean;
            /**
             * Media Ids
             * @default []
             */
            media_ids: number[];
            /** Original Post Id */
            original_post_id?: number | null;
            /** Parent Post Id */
            parent_post_id?: number | null;
            /** Text */
            text?: string | null;
        };
        /** CreateUploadRequest */
        CreateUploadRequest: {
            /** Mime Type */
            mime_type: string;
        };
        /** CreateUploadResponse */
        CreateUploadResponse: {
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Max Bytes */
            max_bytes: number;
            /** Media Id */
            media_id: number;
            /** S3 Key */
            s3_key: string;
            /** Upload Url */
            upload_url: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Description */
            description?: string | null;
            /** Preferred Team Id */
            preferred_team_id?: number | null;
            /** Username */
            username: string;
        };
        /** FeedPage */
        FeedPage: {
            /** Items */
            items: components["schemas"]["PostView"][];
            /** Next Before Id */
            next_before_id: number | null;
        };
        /** GameFiltersOut */
        GameFiltersOut: {
            /** Positions */
            positions: string[];
            /** Seasons */
            seasons: string[];
        };
        /** GameOut */
        GameOut: {
            /** Api Sports Game Id */
            api_sports_game_id: number;
            /** Away Score */
            away_score: number;
            /** Away Team Id */
            away_team_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Home Score */
            home_score: number;
            /** Home Team Id */
            home_team_id: number;
            /** Id */
            id: number;
            /** Player Stats */
            player_stats: {
                [key: string]: unknown;
            }[];
            /** Season */
            season: string;
            /** Venue */
            venue: string | null;
        };
        /** GamesPage */
        GamesPage: {
            /** Items */
            items: components["schemas"]["GameOut"][];
            /** Next Offset */
            next_offset: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveScoreView */
        LiveScoreView: {
            /** Away Score */
            away_score: number;
            /** Game Id */
            game_id: number;
            /** Home Score */
            home_score: number;
            /** Status */
            status: string;
        };
        /**
         * MeOut
         * @description Everything in PublicUserOut plus `date_of_birth` (PII) -- only ever
         *     returned on a path that proves the caller is that profile's own owner
         *     (`POST /users`, `GET /users/me`, `PATCH /users/me`), never on a path
         *     another user can reach.
         */
        MeOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Description */
            description: string | null;
            /** Follower Count */
            follower_count: number;
            /** Following Count */
            following_count: number;
            /** Id */
            id: number;
            /** Preferred Team Id */
            preferred_team_id: number | null;
            /** Profile Picture Media Id */
            profile_picture_media_id: number | null;
            /** Username */
            username: string;
        };
        /** MediaItemView */
        MediaItemView: {
            /** Id */
            id: number;
            /** S3 Key Public */
            s3_key_public: string | null;
            /** S3 Key Thumbnail */
            s3_key_thumbnail: string | null;
        };
        /** MediaOut */
        MediaOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Mime Type */
            mime_type: string | null;
            /** S3 Key Public */
            s3_key_public: string | null;
            /** S3 Key Thumbnail */
            s3_key_thumbnail: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            status: components["schemas"]["MediaStatus"];
        };
        /**
         * MediaStatus
         * @description Linear state chain: UPLOADED -> SCANNING -> PROCESSED | REJECTED.
         *     See app.media.state for the State pattern enforcing legal transitions.
         * @enum {string}
         */
        MediaStatus: "uploaded" | "scanning" | "processed" | "rejected";
        /** NotificationOut */
        NotificationOut: {
            /** Actor User Id */
            actor_user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Recipient User Id */
            recipient_user_id: number;
            /** Reference Id */
            reference_id: number | null;
            type: components["schemas"]["NotificationType"];
        };
        /** NotificationPreferenceOut */
        NotificationPreferenceOut: {
            /** Email Notifications Enabled */
            email_notifications_enabled: boolean;
        };
        /**
         * NotificationType
         * @description Closed set per wiki/CodeContext/Modules/0x05-notifications.md
         *     business rules -- `like` is explicitly excluded, not a 4th value
         *     waiting to happen.
         * @enum {string}
         */
        NotificationType: "follow" | "reply" | "repost";
        /** PostOut */
        PostOut: {
            /** Author Id */
            author_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Reply */
            is_reply: boolean;
            /** Is Repost */
            is_repost: boolean;
            /** Original Post Id */
            original_post_id: number | null;
            /** Parent Post Id */
            parent_post_id: number | null;
            /** Reported */
            reported: boolean;
            /** Text */
            text: string | null;
        };
        /**
         * PostView
         * @description feed/'s (and, per this unit's brief, search/'s) response shape for a
         *     single post. Deliberately its own schema, not app.posts.schemas.PostOut
         *     -- it carries fields (author, like_count, media, mentioned_game_ids,
         *     live_scores) PostOut doesn't, assembled from other modules' read
         *     interfaces rather than the Post row alone.
         */
        PostView: {
            author: components["schemas"]["AuthorView"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is Reply */
            is_reply: boolean;
            /** Is Repost */
            is_repost: boolean;
            /** Like Count */
            like_count: number;
            /** Liked By Viewer */
            liked_by_viewer: boolean;
            /** Live Scores */
            live_scores: components["schemas"]["LiveScoreView"][];
            /** Media */
            media: components["schemas"]["MediaItemView"][];
            /** Mentioned Game Ids */
            mentioned_game_ids: number[];
            /** Original Post Id */
            original_post_id: number | null;
            /** Parent Post Id */
            parent_post_id: number | null;
            /** Text */
            text: string | null;
        };
        /** PostsPage */
        PostsPage: {
            /** Items */
            items: components["schemas"]["PostView"][];
            /** Next Offset */
            next_offset: number | null;
        };
        /**
         * PublicUserOut
         * @description Everything safe to return on the public, unauthenticated
         *     `GET /users/{id}` profile-page read path -- "viewing other users'
         *     account pages" is a public read path per wiki/CodeContext/Modules/
         *     0x01-users.md Security section. No `date_of_birth` here -- see MeOut.
         */
        PublicUserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Follower Count */
            follower_count: number;
            /** Following Count */
            following_count: number;
            /** Id */
            id: number;
            /** Preferred Team Id */
            preferred_team_id: number | null;
            /** Profile Picture Media Id */
            profile_picture_media_id: number | null;
            /** Username */
            username: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Abbreviation */
            abbreviation: string;
            /** Api Sports Team Id */
            api_sports_team_id: number;
            /** Conference */
            conference: string;
            /** Division */
            division: string;
            /** Id */
            id: number;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
        };
        /** ThreadView */
        ThreadView: {
            /** Replies */
            replies: components["schemas"]["PostView"][];
            root: components["schemas"]["PostView"];
        };
        /**
         * UpdateMeRequest
         * @description `PATCH /users/me` body. Uses `model_fields_set` semantics (see
         *     `app.users.service.update_profile`'s `fields_set` parameter): a field
         *     absent from the request body is left untouched; a field present with an
         *     explicit `null` clears it. `username`/`date_of_birth` are deliberately
         *     not fields on this model -- neither is editable via this endpoint.
         */
        UpdateMeRequest: {
            /** Description */
            description?: string | null;
            /** Preferred Team Id */
            preferred_team_id?: number | null;
            /** Profile Picture Media Id */
            profile_picture_media_id?: number | null;
        };
        /** UpdateNotificationPreferenceRequest */
        UpdateNotificationPreferenceRequest: {
            /** Email Notifications Enabled */
            email_notifications_enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_games_events_games_get: {
        parameters: {
            query?: {
                team_id?: number | null;
                season?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_events_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_events_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    get_team_events_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_feed_get: {
        parameters: {
            query?: {
                before_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_feed_thread__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_version_health_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_upload_media_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    get_preference_notifications_preference_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceOut"];
                };
            };
        };
    };
    update_preference_notifications_preference_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreferenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_notification_notifications__notification_id__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    like_posts__post_id__like_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlike_posts__post_id__like_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_replies_posts__post_id__replies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_posts__post_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_accounts_search_accounts_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_games_search_games_get: {
        parameters: {
            query?: {
                season?: string | null;
                team_id?: number | null;
                position?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_filters_search_games_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameFiltersOut"];
                };
            };
        };
    };
    search_posts_search_posts_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_profile_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    delete_me_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_me_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_following_users_me_following_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    get_profile_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_user_users__user_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_user_users__user_id__follow_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
