"""add media table

Revision ID: 532f6a3d06fd
Revises: 2e37a5c1767a
Create Date: 2026-09-17 18:47:37.354869

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '532f6a3d06fd'
down_revision: str | Sequence[str] | None = '2e37a5c1767a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('s3_key_quarantine', sa.Text(), nullable=True),
    sa.Column('s3_key_thumbnail', sa.Text(), nullable=True),
    sa.Column('s3_key_public', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'SCANNING', 'PROCESSED', 'REJECTED', name='media_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
    # Adjusted by hand: autogenerate doesn't emit this, but the native
    # Postgres enum type created for `status` outlives drop_table and would
    # otherwise collide with itself on the next upgrade.
    sa.Enum(name='media_status').drop(op.get_bind(), checkfirst=True)
