"""add deferred FK constraints: media.post_id, users.profile_picture_media_id

Revision ID: 5d905ce8d9e1
Revises: d1c029a3faee
Create Date: 2026-09-17 20:37:18.165202

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d905ce8d9e1'
down_revision: str | Sequence[str] | None = 'd1c029a3faee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_media_post_id_posts', 'media', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('fk_users_profile_picture_media_id_media', 'users', 'media', ['profile_picture_media_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_profile_picture_media_id_media', 'users', type_='foreignkey')
    op.drop_constraint('fk_media_post_id_posts', 'media', type_='foreignkey')
    # ### end Alembic commands ###
