"""add posts tables

Revision ID: d1c029a3faee
Revises: 532f6a3d06fd
Create Date: 2026-09-17 20:21:39.722289

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1c029a3faee'
down_revision: str | Sequence[str] | None = '532f6a3d06fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parent_post_id', sa.BigInteger(), nullable=True),
    sa.Column('is_repost', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('original_post_id', sa.BigInteger(), nullable=True),
    sa.Column('reported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_reply OR parent_post_id IS NOT NULL', name='ck_posts_reply_requires_parent'),
    sa.CheckConstraint('NOT is_repost OR original_post_id IS NOT NULL', name='ck_posts_repost_requires_original'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_original_post_id', 'posts', ['original_post_id'], unique=False)
    op.create_index('ix_posts_parent_post_id', 'posts', ['parent_post_id'], unique=False)
    op.create_table('event_mentions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reporter_id', name='uq_reports_post_reporter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('post_likes')
    op.drop_table('event_mentions')
    op.drop_index('ix_posts_parent_post_id', table_name='posts')
    op.drop_index('ix_posts_original_post_id', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
