"""add search_vector columns and indexes

Revision ID: f4a1c9d2b6e7
Revises: a3f7c2e19b4d
Create Date: 2026-09-18 00:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4a1c9d2b6e7"
down_revision: str | Sequence[str] | None = "a3f7c2e19b4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written, not autogenerated: Alembic's autogenerate doesn't emit
    GENERATED ALWAYS AS (...) STORED for a Computed column added via
    ALTER TABLE, so both generated columns are added with raw op.execute()
    DDL instead, mirroring app.users.models.User.search_vector /
    app.posts.models.Post.search_vector exactly (see
    wiki/CodeContext/Modules/0x07-search.md).
    """
    op.execute(
        "ALTER TABLE users ADD COLUMN search_vector tsvector "
        "GENERATED ALWAYS AS ("
        "to_tsvector('simple', username || ' ' || coalesce(description, ''))"
        ") STORED"
    )
    op.create_index(
        "ix_users_search_vector", "users", ["search_vector"], unique=False, postgresql_using="gin"
    )

    op.execute(
        "ALTER TABLE posts ADD COLUMN search_vector tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', coalesce(text, ''))) STORED"
    )
    op.create_index(
        "ix_posts_search_vector", "posts", ["search_vector"], unique=False, postgresql_using="gin"
    )

    # jsonb_path_ops -- right opclass for @> containment queries
    # specifically (search/'s position filter), see
    # app.events.models.Game's __table_args__.
    op.create_index(
        "ix_games_player_stats_gin",
        "games",
        ["player_stats"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"player_stats": "jsonb_path_ops"},
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_games_player_stats_gin", table_name="games")

    op.drop_index("ix_posts_search_vector", table_name="posts")
    op.execute("ALTER TABLE posts DROP COLUMN search_vector")

    op.drop_index("ix_users_search_vector", table_name="users")
    op.execute("ALTER TABLE users DROP COLUMN search_vector")
